/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp /home/zinface/Desktop/repo.z-tools/z-tools-desktop/intros/org.ayatana.bamf.xml -p bamf -c Bamf -i MetaTypes.h
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef BAMF_H
#define BAMF_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "MetaTypes.h"

/*
 * Proxy class for interface org.ayatana.bamf.control
 */
class Bamf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ayatana.bamf.control"; }

public:
    Bamf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~Bamf();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> CreateLocalDesktopFile(const QString &application)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(application);
        return asyncCallWithArgumentList(QStringLiteral("CreateLocalDesktopFile"), argumentList);
    }

    inline QDBusPendingReply<> InsertDesktopFile(const QString &desktop_path)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(desktop_path);
        return asyncCallWithArgumentList(QStringLiteral("InsertDesktopFile"), argumentList);
    }

    inline Q_DECL_DEPRECATED QDBusPendingReply<> OmNomNomDesktopFile(const QString &desktop_path)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(desktop_path);
        return asyncCallWithArgumentList(QStringLiteral("OmNomNomDesktopFile"), argumentList);
    }

    inline QDBusPendingReply<> Quit()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Quit"), argumentList);
    }

    inline QDBusPendingReply<> RegisterApplicationForPid(const QString &application, int pid)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(application) << QVariant::fromValue(pid);
        return asyncCallWithArgumentList(QStringLiteral("RegisterApplicationForPid"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace ayatana {
    namespace bamf {
      typedef ::Bamf control;
    }
  }
}
#endif
