/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp /home/zinface/Desktop/repo.z-tools/z-tools-desktop/intros/org.ayatana.bamf.view.xml -p view -c View -i MetaTypes.h
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef VIEW_H
#define VIEW_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "MetaTypes.h"

/*
 * Proxy class for interface org.ayatana.bamf.view
 */
class View: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ayatana.bamf.view"; }

public:
    View(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~View();

    Q_PROPERTY(bool Active READ active)
    inline bool active() const
    { return qvariant_cast< bool >(property("Active")); }

    Q_PROPERTY(QString Icon READ icon)
    inline QString icon() const
    { return qvariant_cast< QString >(property("Icon")); }

    Q_PROPERTY(QString Name READ name)
    inline QString name() const
    { return qvariant_cast< QString >(property("Name")); }

    Q_PROPERTY(bool Running READ running)
    inline bool running() const
    { return qvariant_cast< bool >(property("Running")); }

    Q_PROPERTY(bool Starting READ starting)
    inline bool starting() const
    { return qvariant_cast< bool >(property("Starting")); }

    Q_PROPERTY(bool Urgent READ urgent)
    inline bool urgent() const
    { return qvariant_cast< bool >(property("Urgent")); }

    Q_PROPERTY(bool UserVisible READ userVisible)
    inline bool userVisible() const
    { return qvariant_cast< bool >(property("UserVisible")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QStringList> Children()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Children"), argumentList);
    }

    inline Q_DECL_DEPRECATED QDBusPendingReply<QString> Icon()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Icon"), argumentList);
    }

    inline Q_DECL_DEPRECATED QDBusPendingReply<bool> IsActive()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("IsActive"), argumentList);
    }

    inline Q_DECL_DEPRECATED QDBusPendingReply<bool> IsRunning()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("IsRunning"), argumentList);
    }

    inline Q_DECL_DEPRECATED QDBusPendingReply<bool> IsUrgent()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("IsUrgent"), argumentList);
    }

    inline Q_DECL_DEPRECATED QDBusPendingReply<QString> Name()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Name"), argumentList);
    }

    inline QDBusPendingReply<QStringList> Parents()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Parents"), argumentList);
    }

    inline Q_DECL_DEPRECATED QDBusPendingReply<bool> UserVisible()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("UserVisible"), argumentList);
    }

    inline QDBusPendingReply<QString> ViewType()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("ViewType"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    Q_DECL_DEPRECATED void ActiveChanged(bool is_active);
    void ChildAdded(const QString &path);
    void ChildRemoved(const QString &path);
    void Closed();
    Q_DECL_DEPRECATED void NameChanged(const QString &old_name, const QString &new_name);
    Q_DECL_DEPRECATED void RunningChanged(bool is_running);
    Q_DECL_DEPRECATED void UrgentChanged(bool is_urgent);
    Q_DECL_DEPRECATED void UserVisibleChanged(bool user_visible);
};

namespace org {
  namespace ayatana {
    namespace bamf {
      typedef ::View view;
    }
  }
}
#endif
