/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp /home/zinface/Desktop/repo.z-tools/z-tools-desktop/intros/org.ayatana.bamf.window.xml -p window -c Window -i MetaTypes.h
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef WINDOW_H
#define WINDOW_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "MetaTypes.h"

/*
 * Proxy class for interface org.ayatana.bamf.window
 */
class Window: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ayatana.bamf.window"; }

public:
    Window(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~Window();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<uint> GetPid()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("GetPid"), argumentList);
    }

    inline QDBusPendingReply<uint> GetXid()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("GetXid"), argumentList);
    }

    inline QDBusPendingReply<int> Maximized()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Maximized"), argumentList);
    }

    inline QDBusPendingReply<int> Monitor()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Monitor"), argumentList);
    }

    inline QDBusPendingReply<QString> Transient()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Transient"), argumentList);
    }

    inline QDBusPendingReply<uint> WindowType()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("WindowType"), argumentList);
    }

    inline QDBusPendingReply<QString> Xprop(const QString &xprop)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(xprop);
        return asyncCallWithArgumentList(QStringLiteral("Xprop"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void MaximizedChanged(int oldValue, int newValue);
    void MonitorChanged(int oldValue, int newValue);
};

namespace org {
  namespace ayatana {
    namespace bamf {
      typedef ::Window window;
    }
  }
}
#endif
